{{- range .Values.microservices }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ default "prod" $.Values.global.environment }}-microservice-{{ .name }}
  namespace: argocd
spec:
  project: {{ $.Values.global.environment }}-microservices
  destination:
    server: {{ $.Values.global.destinationServer }}
    namespace: {{ .namespace }}
  sources:
  - repoURL: {{ $.Values.global.gitRepo.url }}
    targetRevision: HEAD
    path: charts/microservice
    helm:
      releaseName: {{ .name }}
      valueFiles:
        - $values/values/{{ default "production" $.Values.global.environment }}/microservices/{{ .group }}/{{ .name }}.yaml
  - repoURL: {{ $.Values.global.gitRepo.url }}
    targetRevision: main
    ref: values  # Enables $values ref
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
