apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-microservice-manager
  namespace: argocd
spec:
  project: production-microservices
  source:
    repoURL: https://github.com/nagavijayan-nagarathinam/platform-manager
    chart: charts/argo-apps
    targetRevision: 1.0.0
    helm:
      releaseName: microservice
      valueFiles:
      - values/production/microservices/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated: {prune: true, selfHeal: true}