apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    # Source 1: The official Helm Chart
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 3.3.2
      helm:
        # Reference the values file from the second source using the '$values' alias
        valueFiles:
          - $values/values/platform/addons/argocd/argocd.yaml
    # Source 2: Your Git repository containing the values files
    - repoURL: https://github.com/nagavijayan-nagarathinam/platform-manager
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
