apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-addon-monitoring
  namespace: argocd
spec:
  project: production-addons
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "82.10.1"
      helm:
        releaseName: platform-monitoring
        skipCrds: true
        valueFiles:
          - $values/values/production/addon/monitoring.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "6.53.0"
      helm:
        releaseName: platform-loki
        valueFiles:
          - $values/values/production/addon/loki.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: "6.17.1"
      helm:
        releaseName: platform-promtail
        valueFiles:
          - $values/values/production/addon/promtail.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: "1.24.4"
      helm:
        releaseName: platform-tempo
        valueFiles:
          - $values/values/production/addon/tempo.yaml
    - repoURL: https://github.com/nagavijayan-nagarathinam/platform-manager
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
