apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "generic-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- toYaml .Values.configmap.data | nindent 2 }}
