{{- $istioEnabled := default false .Values.istio.enabled -}}
{{- if and .Values.ingress.enabled (not $istioEnabled) -}}
{{- $fullName := include "generic-service.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "generic-service.name" . }}
    app.kubernetes.io/instance: {{ $fullName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- with .Values.ingress.annotations }}
{{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Release.Name }}
            port:
              number: {{ $.Values.service.port }}
      {{- end }}
  {{- end }}
{{- end }}
{{- if $istioEnabled }}
{{- $gatewayName := default (printf "%s-gateway" .Release.Name) .Values.istio.gateway.name -}}
{{- $istioHosts := .Values.istio.hosts -}}
{{- if eq (len $istioHosts) 0 -}}
{{- range .Values.ingress.hosts }}
{{- $istioHosts = append $istioHosts .host -}}
{{- end -}}
{{- end -}}
{{- $istioGateways := .Values.istio.gateways -}}
{{- if eq (len $istioGateways) 0 -}}
{{- if .Values.istio.gateway.enabled -}}
{{- $istioGateways = list $gatewayName -}}
{{- else -}}
{{- $istioGateways = list "istio-system/platform-gateway" -}}
{{- end -}}
{{- end -}}
---
{{- if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $gatewayName }}
spec:
  selector:
{{ toYaml .Values.istio.gateway.selector | nindent 4 }}
  servers:
  {{- range $istioHosts }}
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - {{ . | quote }}
  {{- end }}
---
{{- end }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  hosts:
  {{- range $istioHosts }}
    - {{ . | quote }}
  {{- end }}
  gateways:
  {{- range $istioGateways }}
    - {{ . }}
  {{- end }}
  http:
    - match:
      {{- range .Values.ingress.hosts }}
        {{- range .paths }}
        - uri:
            prefix: {{ .path | quote }}
        {{- end }}
      {{- end }}
      route:
        - destination:
            host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
{{- end }}
